# Generated by Django 3.1.2 on 2021-09-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_auto_20210902_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_app.designation'),
        ),
    ]
