# Generated by Django 3.1.2 on 2021-09-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_employee_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
