# Generated by Django 3.1.2 on 2021-09-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_auto_20210904_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
